version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:docker@db:5432/nestjs_db?schema=sample
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: