version: '3.7'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: